server:
  port: 8082

spring:
  application:
    name: emp-proviter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wub?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
        time-between-eviction-runs: 10000
  jpa:
    hibernate:
      ddl-auto: update


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


mybatis:
  type-aliases-package: com.jk.gy.pojo
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

