server:
  port: 8083

spring:
  application:
    name: feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true